hw1
yarsult/go-proj1 pull request #1
Opened 2024-10-09 14:26 UTC by yarsult

@hexzedels
@antonvlasov

2024-10-12 21:49 UTC, hexzedels commented
FYI val1 = Value{kind: "D", st: "", d: val} при инициализации структур и переменных можно не указывать явно дефолтные значения (в твоем случае стрингу) 
Строчку выше можно переписать, как:
val1 = Value{kind: "D", d: val}

2024-10-12 21:50 UTC, hexzedels commented
Лучше использовать константы для типов значений. Например, 
`
type Kind string

const (
KindString Kind = "S"
KindInt Kind = "D"
)
`

2024-10-12 21:52 UTC, hexzedels commented
FYI конструкции такого типа следует писать без else

```go
	if res.kind == "S" {
		return &(res).st
	} else {
		return &(res).d
	}
```

```go
	if res.kind == "S" {
		return &(res).st
	} 
		return &(res).d
```

2024-10-12 21:54 UTC, hexzedels commented
Не забывай делать пустую строку между любыми двумя функциями. В целом старайся применять гошное автоформатирование, если работаешь в IDE (установи плагины все нужные для своей IDE)

Также добавь в gitignore .DS_Store  файлы.

2024-10-12 21:55 UTC, hexzedels requested changes
Смотри комменты выше

2024-10-17 13:16 UTC, antonvlasov reviewed
Не нужно заливать бинарные файлы в репо, сделай .gitignore

2024-10-20 14:38 UTC, closed without merging